"""empty message

Revision ID: 1a21452a366e
Revises: 8b456a060f44
Create Date: 2025-04-24 01:07:40.083282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a21452a366e'
down_revision = '8b456a060f44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand_market_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('brand_market_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('tech_infra_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tech_infra_reason', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_column('tech_infra_reason')
        batch_op.drop_column('tech_infra_score')
        batch_op.drop_column('brand_market_reason')
        batch_op.drop_column('brand_market_score')

    # ### end Alembic commands ###
