"""empty message

Revision ID: 97a0928b6476
Revises: 1a21452a366e
Create Date: 2025-04-25 08:18:25.253763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97a0928b6476'
down_revision = '1a21452a366e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand_market_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('tech_infra_status', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_column('tech_infra_status')
        batch_op.drop_column('brand_market_status')

    # ### end Alembic commands ###
